[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "drogue-device"
version = "0.1.0"

[lib]
doctest = false

[dependencies]
embassy = { version = "0.1.0", default-features = false, features = ["executor-agnostic"] }
embassy-hal-common = { version = "0.1.0", default-features = false }

# LoRa dependencies
lorawan-device = { git = "https://github.com/lulf/rust-lorawan.git", rev = "a373d06fa8858d251bc70d5789cebcd9a638ec42", default-features = false, features = ["async"], optional = true }
lorawan-encoding = { git = "https://github.com/lulf/rust-lorawan.git", rev = "a373d06fa8858d251bc70d5789cebcd9a638ec42", default-features = false, features = ["default-crypto"], optional = true }
#lorawan-encoding = { path = "../../../rust-lorawan/encoding", default-features = false, features = ["default-crypto", "defmt", "defmt-trace"], optional = true }
#lorawan-device = { path = "../../../rust-lorawan/device", default-features = false, optional = true, features = ["defmt-trace", "withdefmt", "async"] }

bit_field = { version = "0.10", optional = true }
embassy-stm32 = { version = "0.1.0", default-features = false, optional = true }
#embassy-stm32 = {path = "../../../embassy/embassy-stm32", default-features = false, optional = true }

# Wifi Dependencies
nom = { version = "6.1.2", default-features = false, optional = true }
moveslice = { version = "2.0", optional = true }

# TLS dependency
drogue-tls = { git = "https://github.com/drogue-iot/drogue-tls.git", rev = "59cb23017f546da8e0f186042758226165400548", default-features = false, features = ["async"], optional = true}
#drogue-tls = {path = "../../drogue-tls", default-features = false, features = ["async"], optional = true}
rand_core = { version = "0.6.2", default-features = false, optional = true }

# Utilities
futures = { version = "0.3", default-features = false }
heapless = "0.7"
embedded-hal = { version = "0.2", features = ["unproven"] }
atomic-polyfill = "0.1"
critical-section = "0.2.3"

# Logging alternatives
log = { version = "0.4", optional = true }
defmt = { version = "0.2", optional = true }

# HTTP dependencies
base64 = { version = "0.13.0", default-features = false }

[dev-dependencies]
embassy = { version = "0.1.0", features = ["std", "time", "time-tick-1mhz"]}
#embassy = {path = "../../../embassy/embassy", features = ["std", "time", "time-tick-1mhz"]}

drogue-device-macros = { path = "../macros" }
futures = { version = "0.3", default-features = false, features = ["executor"] }
arrayvec = { version = "0.6" }

[features]
default = [ "std", "log", "time" ]
std = ["embassy/std", "embassy/time"]
"lora+sx127x" = ["lorawan-device", "lorawan-encoding", "bit_field", "lora", "embassy/time"]
"lora+stm32wl" = ["lorawan-device", "lorawan-encoding", "bit_field", "embassy-stm32/subghz", "lora", "embassy/time"]
"lora+rak811" = ["nom", "moveslice"]
"wifi+esp8266" = ["nom", "moveslice"]
"wifi+eswifi" = ["nom", "moveslice"]
time = []
lora = ["rand_core"]
wifi = []
fonts = []
tls = ["drogue-tls", "rand_core"]

defmt-default = [ ]
defmt-trace = [ ]
defmt-debug = [ ]
defmt-info = [ ]
defmt-warn = [ ]
defmt-error = [ ]
